### ISSUE TITLE
bug in 0.1.1

### ISSUE THREAD

**Issue by cugxy** [cmollet/epsg_ident#8]
I use the wkt like this `PROJCS[\"UTM Zone 50, Northern Hemisphere\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9108\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",117],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],UNIT[\"Meter\",1]]` to find the epsg code, it is ok in mac os, but error in windows, I found that the wkt do not in the database esri_epsg.db, but ok in mac os. than we replace the esri_epsg.db file. it worked.

**Comment by cmollet** [comment]
Hi @cugxy ,

Could you provide a little more information about the exact steps to reproduce this bug? It sounds like you were using the Python API and instantiating directly with this WKT string as the `prj` parameter? What was the exact error message you got? Something permissions related?

**Comment by cugxy** [comment]
ennnn, the WKT string that we talk, is not in the database, than ,the code use `call_api`, but if the network is not reachable , the function  `call_api` well hold the thread.

**Comment by cmollet** [comment]
You can disable the `call_api` when instantiating:

```py
ident = Sridentify(call_remote_api=False)
```

or by passing the `-n` flag when running from the command line. It will just return `None` in that case instead of blocking. See #4 

This was somewhat recently added; make sure you're running the latest version: `pip install --user --upgrade sridentify`

**Comment by cugxy** [comment]
ok thanks, but I would like to have some function like this, it allowed me to add the WKT string and EPSG code to the database. Or this Python package DO HAS the function, but I don't know.

**Comment by cmollet** [comment]
You could do that, assuming you know the EPSG code of the WKT string, by instantiating and setting `self.prj` to the WKT string and `self.epsg_code` to the epsg code and then calling the `save_to_db` method , e.g.

```py
ident = Sridentify(prj="""PROJCS[UTM Zone 50...""", epsg_code=32650)
ident.save_to_db()
```
And it should be saved to the database. This may raise some permission errors if you didn't install it with `pip install --user`, because the user running `sridentify` must have write permission where the database is located in the filesystem.

**Comment by cugxy** [comment]
ok, thanks
